### ISSUE TITLE
configmgr schema validation regression on null, required fields

### ISSUE THREAD

**Issue by 1000TurquoisePogs** [zowe/zowe-common-c#458]
v2.16.0's bugfix of yaml nulls being treated as strings https://github.com/zowe/zowe-common-c/issues/435 has caused user bugs from configs prior to v2.9.0 (June 2023),

Before that time, users of keyrings would have in their configs

```
pem:
  key:
  certificate:
  certificateAuthority:
  - A
  - B
```

key & certificate are listed as "required" fields. So, though configmgr is now correctly identifying this as invalid (a required field shouldnt be null), users depended upon this and thus we should restore this behavior until for example v3.
